version: "3.8"

services:
  psql:
    container_name: psql
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fampay
    networks:
      - default