version: '3'

tasks:
  build:
    cmds:
      - go build -o bin/api main.go
  gen:
    dir: ./api/pkg/routes/
    cmds:
      - go run github.com/deepmap/oapi-codegen/cmd/oapi-codegen --config=oapi-codegen.yaml ./openapi-spec.yaml
  api:
    cmds:
      - go run main.go api
    env:
      PORT: 3000
  fetch:
    cmds:
      - go run main.go youtube-fetcher
  migrate:
    cmds:
      - go run main.go migrate  