name: release

on:
  push:
    branches:
      - main

jobs:
  tagger:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.REPO_BUILDER_TOKEN }}
          release_branches: main
          pre_release_branches: release-1
          append_to_pre_release_tag: rc
  release:
    needs: tagger
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_BUILDER_TOKEN }}
      - run: git config --global url.https://${{ secrets.REPO_BUILDER_TOKEN }}@github.com/.insteadOf https://github.com/
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.21'
          cache: true
      - name: Run Goreleaser for release in dev branch
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean 
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_BUILDER_TOKEN }}